### ISSUE TITLE
getting start with your library

### ISSUE THREAD

**Issue by unipsycho** [ghasemkiani/binance-chain#1]
Hi, i'm fairly new to nodejs, but done a few projects and lots of python work, anyway, i'm having troubles starting with your library,  Do you have any simple example of getting your balance or open trades you can share on the process of running the first function after install with node?  Would love to use the dex with node, I've not been able to get the python libraries to compile on windows so thought this might be a good idea to try yours.

**Comment by ghasemkiani** [comment]
Hi

This package in its current form is still very crude and needs a lot of work. However, you could inspect it to see how you can use the `@binance-chain/javascript-sdk` package.

As a simple example, say you create a project called `test-app`:

```
md test-app
cd test-app
npm init --yes
npm i github:ghasemkiani/binance-chain
```
Now create a js file, e.g. `app.js` like this:
```
const {Dex} = require("@ghasemkiani/binance-chain/dex");

async function main() {
	let address = "bnbyouraddress...";
	let dex = new Dex({address});
	await dex.toGetAccount();
	console.log(dex.balances);
}

main()
.then(process.exit)
.catch(console.log);
```
Now run it with `node app.js`. I hope this helps.
